# Generated by Django 4.1.3 on 2024-11-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingappapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='chores', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='locked_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
