# Generated by Django 5.1.3 on 2024-11-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingappapi', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dates',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
