# Generated by Django 4.1.3 on 2024-12-03 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulingappapi', '0005_schedule_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulingappapi.day'),
        ),
    ]
